name: CI

on:
  push:
    branches: [ github-ci-wip ]
  pull_request:
    branches: [ github-ci-wip ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup database server for testing
      run: ci/setup_test.bash
      env:
        PGVERSION: 12

    - name: Test
      run: go test -v ./...
      env:
        PGX_TEST_CONN_STRING: postgres://pgx_md5:secret@127.0.0.1/pgx_test
        PGX_TEST_UNIX_SOCKET_CONN_STRING: "host=/var/run/postgresql dbname=pgx_test"
        PGX_TEST_TCP_CONN_STRING: postgres://pgx_md5:secret@127.0.0.1/pgx_test
        PGX_TEST_TLS_CONN_STRING: postgres://pgx_md5:secret@127.0.0.1/pgx_test?sslmode=require
        PGX_TEST_MD5_PASSWORD_CONN_STRING: postgres://pgx_md5:secret@127.0.0.1/pgx_test
        PGX_TEST_PLAIN_PASSWORD_CONN_STRING: postgres://pgx_pw:secret@127.0.0.1/pgx_test
